### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by conorpp** [RobertCNelson/elftosb#1]
Any chance you can update with latest ELF2USB from NXP or give any pointers to it?

**Comment by RobertCNelson** [comment]
@conorpp would you restate that question? This repo is for "elftosb", but you said "ELF2USB"...

Which i found in: https://www.nxp.com/docs/en/application-note/AN12278.pdf

![elf2usb](https://user-images.githubusercontent.com/91469/70179366-8e3c0580-16a3-11ea-9a7f-fda486eea7c8.png)

So... How does this apply to elftosb???

Regards,

**Comment by conorpp** [comment]
My mistake, I mean elftousb, I think it's the same tool.  Also I checked LPCXpresso55S69 SDK, and it's elftousb in there as well (so the AN has a typo).  No source code in LPCXpresso55S69 SDK though :(

**Comment by RobertCNelson** [comment]
@conorpp, well sorry, i have no idea where NXP keeps there current version of elftosb... I got this years ago from http://repository.timesys.com/buildsources/e/elftosb/ , at the time i needed it for the i.mx23.. However u-boot eventually grew the ability to generate the *.sb output, thus I personally haven't needed it for years.

It's only still have it on github for archival purposes..

Regards,

**Comment by conorpp** [comment]
No worries, thanks though :)
